version: '3.7'

services:
  # PostgreSQL with PostGIS extension
  db:
    image: postgis/postgis:16-3.4
    container_name: tracewing_db
    environment:
      POSTGRES_DB: ${DB_NAME:-tracewing_db}
      POSTGRES_USER: ${DB_USER:-tracewing_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-tracewing_password}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-tracewing_user} -d ${DB_NAME:-tracewing_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tracewing_network

  # Redis for caching and Celery broker
  redis:
    image: redis:7-alpine
    container_name: tracewing_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tracewing_network

  # Django Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: tracewing_backend
    command: /wait-for-it.sh db 5432 -- /wait-for-it.sh redis 6379 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tracewing_network

  # Celery Worker
  celery:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: tracewing_celery
    command: /wait-for-it.sh db 5432 -- /wait-for-it.sh redis 6379 -- celery -A tracewing worker --loglevel=info
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tracewing_network

  # Celery Beat (Scheduler)
  celery-beat:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: tracewing_celery_beat
    command: /wait-for-it.sh db 5432 -- /wait-for-it.sh redis 6379 -- celery -A tracewing beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - tracewing_network

  # React Dashboard
  dashboard:
    build: 
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: tracewing_dashboard
    volumes:
      - ./dashboard:/app
      - dashboard_node_modules:/app/node_modules
    ports:
      - "3001:3000"
    env_file:
      - ./dashboard/.env
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - tracewing_network

  # React Native Mobile (Optional)
  mobile:
    build: 
      context: ./mobile
      dockerfile: Dockerfile
    container_name: tracewing_mobile
    volumes:
      - ./mobile:/app
      - mobile_node_modules:/app/node_modules
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    env_file:
      - ./mobile/.env
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - EXPO_USE_FAST_REFRESH=true
    depends_on:
      - backend
    networks:
      - tracewing_network
    profiles:
      - mobile

volumes:
  postgres_data:
  redis_data:
  backend_static:
  backend_media:
  dashboard_node_modules:
  mobile_node_modules:

networks:
  tracewing_network:
    driver: bridge 