# Generated by Django 5.2.4 on 2025-08-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('branch', 'Branch'), ('site', 'Site'), ('client', 'Client Location')], default='office', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius', models.IntegerField(default=100, help_text='Radius in meters')),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('action', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('location_update', 'Location Update')], max_length=20)),
                ('is_within_geofence', models.BooleanField(default=False)),
                ('distance_from_geofence', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('geofence_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geofencing.geofencelocation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
